### ISSUE TITLE
Test setup will not work with Chrome 76

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-apps-feature-tests#1]
I am currently unable to run the feature tests after upgrading to Chromium v76.x. I get:

    session not created: Chrome version must be between 71 and 75
        (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 5.0.0-25-generic x86_64) (Selenium::WebDriver::Error::SessionNotCreatedError)

The `chromedriver-helper` gem is now deprecated, and can't be updated to a version that supports Chrome 76. Instead, we are recommended to switch to the `webdrivers` gem. However, having made that switch I am unable to run the tests. Instead I get:

    Selenium::WebDriver::Error::WebDriverError:         
    Selenium::WebDriver::Error::WebDriverError: unable to connect 
    to chromedriver 127.0.0.1:9515

I have tried various workarounds for this, but currently do not have working feature tests on my machine.

**Comment by bwmcbride** [comment]
@ijdickinson is this still an active issue?

As I recall, it worked fine for me and for you on your work machine.

**Comment by ijdickinson** [comment]
`chromedriver-helper` is definitely deprecated, so I think we need to make a change here anyway. See: https://github.com/flavorjones/chromedriver-helper

**Comment by ijdickinson** [comment]
Closing as obsolete.
